server:
  port: 9000
spring:
  datasource:
    username: root
    password: xieqiqi037005
    url: jdbc:mysql://127.0.0.1:3306/store_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    application:
      name: store-product
